name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: step-1
        run: ls -ltr /usr/bin
      - name: step-2
        run: /usr/bin/python3.9 -m venv .venv
      - name: step-2-1
        run: /usr/bin/python3.9 --version
      - name: step-3
        run: source /home/azureuser/.venv/bin/activate
      - name: step-4
        run: /home/azureuser/.venv/bin/pip install contentctl
      - name: step-5
        run: contentctl validate
