name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: step-1
        run: /usr/bin/python3.9 -m venv .venv
      - name: step-2
        run: |
          source /home/splunker/.venv/bin/activate
          cd /home/splunker/demo
          contentctl validate
      - name: step-3
        run: |
          source /home/splunker/.venv/bin/activate
          cd /home/splunker/demo
          contentctl test
